server:
  port: 8080

spring:
  application:
    name: finance-tracker

  # Kết nối Database (Khớp với docker-compose)
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase 
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo bảng từ Entity của Tâm
    show-sql: true # Hiện log SQL để Tâm dễ debug
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true # Thêm cái này để log SQL có màu cho đẹp Tâm nè

  # Kết nối Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Kết nối Elasticsearch
  # Elasticsearch (Cập nhật bản mới)
  elasticsearch:
    client:
      uris: http://localhost:9200
    
  # Kết nối RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

  cache:
    type: redis
    
# 🛡️ PHẦN MỚI: Cấu hình Circuit Breaker (Cùng hàng với 'spring')
resilience4j:
  circuitbreaker:
    instances:
      esService: # Phải khớp với name ở Annotation @CircuitBreaker
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3

# 📜 PHẦN MỚI: Cấu hình Logging để xem Đa luồng
logging:
  level:
    root: INFO
    "[com.tam.finance_tracker]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Cấu hình Swagger để nhà tuyển dụng xem API
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    # Nếu có biến môi trường JWT_SECRET thì dùng, không thì dùng cái mặc định sau dấu :
    secret: ${JWT_SECRET:TamVip130IQFinanceTrackerSecretKey2026_MustBeLongAndSecure}
    expiration-ms: ${JWT_EXPIRATION:86400000} # 1 ngày